### ISSUE TITLE
missing module megalodon_extension

### ISSUE THREAD

**Issue by lileica** [XuezheMax/megalodon#9]
I encountered an error while using your source code:

```
import megalodon_extension.ops as megalodon_ops
ModuleNotFoundError: No module named 'megalodon_extension'
```

![image](https://github.com/user-attachments/assets/ab9da5c2-cf09-4513-a709-26f8e63b8c32)

I've been digging through the code you provided, but I can't seem to find this "megalodon_extension" thing anywhere. Any ideas on how to fix this? Thanks

**Comment by XuezheMax** [comment]
Hi @lileica,

Thanks for your question. For the `megalodon_extension` module, it is the fused CUDA kernels in the folder https://github.com/XuezheMax/megalodon/tree/main/megalodon/csrc
In order to use it, you need to first compile the CUDA code by entering the root folder of the repo and executing: 
```
pip install -e .
```
or 
```
python setup.py develop
```

Please let me know if you have other questions.

**Comment by lileica** [comment]
I forgot to install Megalodon. I've tried 
`python setup.py develop `，
but there's a new error:

### Traceback (most recent call last):
  File "/home/bingxing2/home/XXXX/soft/pipeline-master/megalodon/megalodon-main/setup.py", line 65, in <module>
    main()
  File "/home/bingxing2/home/XXXX/soft/pipeline-master/megalodon/megalodon-main/setup.py", line 48, in main
    setup(
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
    self.run_command(cmd)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
    cmd_obj.run()
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/command/develop.py", line 113, in install_for_development
    self.run_command('build_ext')
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
    cmd_obj.run()
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 93, in run
    _build_ext.run(self)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 605, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bingxing2/home/XXXX/.conda/envs/megalodonEnv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
    ~~~~~~~~~^^^^
IndexError: list index out of range

**What should I do to fix this issue?**

**Comment by XuezheMax** [comment]
You need to specify the gpu arch version before compiling the code.
